# Generated by Django 4.2.17 on 2024-12-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organ', models.CharField(choices=[('Heart', 'Heart'), ('Liver', 'Liver'), ('Lungs', 'Lungs'), ('Kidney', 'Kidney'), ('Eyes', 'Eyes')], max_length=50)),
                ('blood_type', models.CharField(max_length=3)),
                ('availability', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
