# Generated by Django 4.2.17 on 2024-12-29 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='blood_type',
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='o+', max_length=3),
        ),
        migrations.AddField(
            model_name='donor',
            name='hiv_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donor',
            name='willing_to_donate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='organ',
            field=models.CharField(choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('eyes', 'Eyes'), ('liver', 'Liver')], max_length=50),
        ),
    ]
