# Generated by Django 4.2.17 on 2024-12-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='organ_needed',
        ),
        migrations.AddField(
            model_name='recipient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=3),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='organ',
            field=models.CharField(choices=[('kidney', 'Kidney'), ('heart', 'Heart'), ('lungs', 'Lungs'), ('eyes', 'Eyes'), ('liver', 'Liver')], default='kidney', max_length=10),
        ),
    ]
